runtime: nodejs14

# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  DB_USER: MY_DB_USER
  DB_PASS: MY_DB_PASSWORD
  DB_NAME: MY_DATABASE
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  CLOUD_SQL_CONNECTION_NAME: <MY-PROJECT>:<INSTANCE-REGION>:<MY-DATABASE>